import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import ContractService from '../services/contractService';
import WalletService from '../services/walletService';
import ConnextService from '../services/connextService';

interface HomePageProps {
  // Add any props specific to the HomePage component
}

const HomePage: NextPage<HomePageProps> = () => {
  const [relayerFee, setRelayerFee] = useState(0);

  // TODO: get provider from wagmi
  const contractService = new ContractService(provider);
  const walletService = new WalletService(contractService, provider);
  const connextService = new ConnextService({
    signerAddress,
    network: "testnet",
    chains: {
      // TODO: get chains
    },
    walletService
  });

  const handleGreet = () => {
    // TODO: send the xcall
    // setRelayerFee(connextService.getRelayerFee(...));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Connext Next JS</title>
        <meta content="Generated by @connext/sdk" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <div className={styles.flexDisplay}>
          <h2>Connext Chain Abstraction Reference</h2>
          <ConnectButton />
        </div>
        <div className={styles.center}>
          <button className={styles.button} onClick={() => handleGreet()}>
            Greet With Tokens
          </button>
          {/* {tracker && (
            <p>
              You can track you xcall{" "}
              <a target="_blank" href={tracker} rel="noreferrer">
                here.
              </a>
            </p>
          )} */}
        </div>
        <div>

        </div>
      </main>
      <footer className={styles.footer}>
        For more information refer to the official Connext
        documentation{" "}
        <a
          href="https://docs.connext.network/"
          target="_blank"
          rel="noreferrer"
        >
          here
        </a>
        .
      </footer>
    </div>
  );
};

export default HomePage;
